[package]
name = "method1"
version = "0.1.0"
edition = "2024"

[build-dependencies]
cxx-qt-build.workspace = true

[dependencies]
cxx.workspace = true
cxx-qt.workspace = true
cxx-qt-lib.workspace = true
notify.workspace = true
